name: CD

on:
  push:
    tags: 
      release-v* 

jobs:
  install: # 安装任务
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ["12"]
    name: install 
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      # Setup node with version 12.x and NPM registry url
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          registry-url: "https://registry.npmjs.org"
      # install yarn
      - name: Install yarn 
        run: npm install yarn
      # restore cache
      - name: Cache node_modules
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            node_modules
            packages/**/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      # run yarn install to install dependencies
      - name: Install dependencies
        run: yarn
  test: # 测试任务
    needs: install
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ["12"]
    name: test
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Load node_modules
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            node_modules
            packages/**/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Test
        run: yarn test
  build: # 构建
    name: Build
    runs-on: ubuntu-latest
    needs: [install, test]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Load node_modules
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            node_modules
            packages/**/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Build
        run: yarn build
  publish: # 发布npm
    name: Publish
    runs-on: ubuntu-latest
    needs: [install, test, build]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Load node_modules
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            node_modules
            packages/**/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Merge master branch
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: uat
          github_token: ${{ github.token }}
      - name: Lerna publish
        run: |
          lerna publish from-package --no-verify-access --yes
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 