name: GitHub Actions Demo

on: [push]

strategy:
  matrix:
    os: [ubuntu-latest]
    node: ["12"]

name: test - ${{ matrix.os }} - ${{ matrix.node }}
runs-on: ${{ matrix.os }}

jobs:
  install: # 安装任务
    name: install yarn - ${{ martix.os }} - ${{ martix.node }}
    runs-on: ${{ martix.os }}
    steps:
      # Setup node with version 12.x and NPM registry url
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: ${{ martix.node }}
          registry-url: "https://registry.npmjs.org"
      # install yarn
      - name: Install yarn 
        run: npm install yarn
      # run yarn install to install dependencies
      - name: Install dependencies
        run: |
          yarn install
